In [2]:
import numpy as np
import numpy.linalg as la

#### Costruzione matrice A 2x2

In [3]:
A = np.array([[1, -2],
              [-3, 2]])
A

array([[ 1, -2],
       [-3,  2]])

#### Autovalori e autovettori di A

In [4]:
ls, V = la.eig(A)
ind = np.argsort(ls)[::-1]
ls = ls[ind]
V = V[:,ind]
print('Autovalori:',ls)
print('Matrice autovettori:\n',V)

Autovalori: [ 4. -1.]
Matrice autovettori:
 [[ 0.5547002  -0.70710678]
 [-0.83205029 -0.70710678]]


#### Autovettori calcolati a mano

In [5]:
v1 = np.array([-2,3])
v2 = np.array([1,1])

#### Normalizzazione degli autovettori calcolati a mano

In [6]:
vn1 = v1/(la.norm(v1))
print('Autovettore 1 calcolato a mano e normalizzato:', vn1)
print('Autovettore 1 da matrice V:', V[:,0])

Autovettore 1 calcolato a mano e normalizzato: [-0.5547002   0.83205029]
Autovettore 1 da matrice V: [ 0.5547002  -0.83205029]


In [7]:
vn2 = v2/(la.norm(v2))
print('Autovettore 1 calcolato a mano e normalizzato:', vn2)
print('Autovettore 1 da matrice V:', V[:,1])

Autovettore 1 calcolato a mano e normalizzato: [ 0.70710678  0.70710678]
Autovettore 1 da matrice V: [-0.70710678 -0.70710678]


#### Vettore a

In [8]:
a = np.array([-1,1/2])
a

array([-1. ,  0.5])

#### Applicazione della matrice A al vettore a

In [9]:
A.dot(a)

array([-2.,  4.])

#### Calcolo componenti di $a$ su $v_1$ e $v_2$: $\alpha$ e $\beta$

In [10]:
beta = (a[0]*vn1[1]/vn1[0] - a[1])/(vn2[0]*vn1[1]/vn1[0] - vn2[1])
alfa = (a[0] - beta*vn2[1])/vn1[0]
print('Alfa:',alfa)
print('Beta',beta)

Alfa: 1.08166538264
Beta -0.565685424949


#### Somma delle componenti $\alpha$ e $\beta$ di $a$ sulle direzioni degli autovettori moltiplicate per gli autovalori corrispondenti

In [11]:
alfa*vn1*ls[0] + beta*vn2*ls[1]

array([-2.,  4.])

In [12]:
X = np.array([[1,1],[0,1]])
X

array([[1, 1],
       [0, 1]])

In [14]:
ls, V = la.eig(X)
ind = np.argsort(ls)[::-1]
ls = ls[ind]
V = V[:,ind]
print('Autovalori:',ls)
print('Matrice autovettori:\n',V)

Autovalori: [ 1.  1.]
Matrice autovettori:
 [[ -1.00000000e+00   1.00000000e+00]
 [  2.22044605e-16   0.00000000e+00]]


In [15]:
V_1 = la.inv(V)
V_1

array([[  0.00000000e+00,   4.50359963e+15],
       [  1.00000000e+00,   4.50359963e+15]])