In [1]:
import numpy as np
import numpy.linalg as la

#### Costruzione matrice A 2x2

In [2]:
A = np.array([[1, -2],
              [-3, 2]])
A

array([[ 1, -2],
       [-3,  2]])

#### Autovalori e autovettori di A

In [3]:
ls, V = la.eig(A)
ind = np.argsort(ls)[::-1]
ls = ls[ind]
V = V[:,ind]
print('Autovalori:',ls)
print('Matrice autovettori:\n',V)

Autovalori: [ 4. -1.]
Matrice autovettori:
 [[ 0.5547002  -0.70710678]
 [-0.83205029 -0.70710678]]


#### Creazione matrice autovalori

In [4]:
L = np.diag(ls)
L

array([[ 4.,  0.],
       [ 0., -1.]])

#### Matrice inversa degli autovettori $\Lambda$

In [5]:
V_1 = la.inv(V)
V_1

array([[ 0.72111026, -0.72111026],
       [-0.84852814, -0.56568542]])

$\Lambda = V^{-1} \cdot A \cdot V$

In [6]:
V_1.dot(A.dot(V))

array([[  4.00000000e+00,   0.00000000e+00],
       [  6.66133815e-16,  -1.00000000e+00]])

$A = V \cdot \Lambda \cdot V^{-1}$

In [7]:
V.dot(L.dot(V_1))

array([[ 1., -2.],
       [-3.,  2.]])

#### Definizione vettore a = [-1,1/2]

In [8]:
a = np.array([-1,1/2])
a

array([-1. ,  0.5])

#### Applicazione matrice A a x

In [9]:
b = A.dot(a)
b

array([-2.,  4.])

$\Lambda \cdot V^{-1} \cdot a = V^{-1} \cdot A \cdot a$

In [10]:
L.dot(V_1.dot(a))

array([-4.32666153, -0.56568542])

In [11]:
V_1.dot(A.dot(a))

array([-4.32666153, -0.56568542])